export const CREATE_COMPONENT = 'CREATE_COMPONENT';
export const CREATE_COMPONENT_START = 'CREATE_COMPONENT_START';
export const CREATE_COMPONENT_SUCCESS = 'CREATE_COMPONENT_SUCCESS';

export const LOAD_COMPONENTS = 'LOAD_COMPONENTS';
export const ADD_COMPONENTS = 'ADD_COMPONENTS';

export const UPDATE_COMPONENT = 'UPDATE_COMPONENT';
export const UPDATE_COMPONENTABLE = 'UPDATE_COMPONENTABLE';

export const TOGGLE_TAB = 'TOGGLE_TAB';

export const DELETE_COMPONENT = 'DELETE_COMPONENT';
export const DELETE_COMPONENT_SUCCESS = 'DELETE_COMPONENT_SUCCESS';

export const SET_ACTIVE_COMPONENT = 'SET_ACTIVE_COMPONENT';

export const REORDER_COMPONENTS = 'REORDER_COMPONENTS';

export const UPDATE_COMPONENTS = 'UPDATE_COMPONENTS';
export const UPDATE_COMPONENTS_START = 'UPDATE_COMPONENTS_START';
export const UPDATE_COMPONENTS_SUCCESS = 'UPDATE_COMPONENTS_SUCCESS';

export const SET_SHIFT_STATUS = 'SET_SHIFT_STATUS';

export const SET_EDITOR_HEIGHT = 'SET_EDITOR_HEIGHT';

